### ISSUE TITLE
AFILinkerBot Mental Breakdown

### ISSUE THREAD

**Issue by Acidion** [HadManySons/AFILinkerBot#3]
As shown in this post: https://www.reddit.com/r/AirForce/comments/6gq4sv/eo_or_let_it_go/dismg1g/ AFILinkerBot seems to sometimes have a mental breakdown (probably too much salt in the interweb-tubes).

Looking through the output that was posted in that link, it appears that the bot grabbed the object for the whole AFI table. I'll try taking a look into how the bot is choosing what to output to see why there might be this inconsistency.

**Comment by Acidion** [comment]
So after looking through the code a little bit, it looks like a quick and dirty fix would be to throw an else if in the for loop starting at line 201. This check would need to do some regex magic to ensure that the 'link' object doesn't start with http://static.e-publishing.af.mil/production/1/ (+ infinite follow on characters). This would be a good spot to throw in a log entry with possibly some overall object status to help debug why this is happening.

I'll try and take a look at the code later on when I'm not stuck at my work desk and have a proper IDE to mess around with, unless someone else gets to it first.

**Comment by HadManySons** [comment]
Yeah, I have suspect that the vomit is coming from a bad return from ePubs but the regex check would at least prevent it from being posted in the interim. A more long term solution would be check for garbage and the query ePubs again, hoping for a good return. I'll try to work on the temp solution tonight as well (JST) and if you get to it too, we can look at which works better or combine our efforts

**Comment by HadManySons** [comment]
Look at the code I included, added stuff to line 202, since "CDATA" was present in all the garbage returns. For now, the code will just reject the link and move onto any other, not re-attempt to acquire the link. I think for that, I'll have to compartmentalize the code into functions.

`# Parse through results and start building the
 # TotalAFILinks and TotalSearchLinks variables
                        for link in epubsSearchForAllLinesWithPDF:
                            if "CDATA" in link:
                                print("Garbage return, skipping link")
                                continue
                            if link in formattedComment:
                                print(str(individualMention.group()).upper() + " link already posted by OP, skipping")
                            else:
                                # Add the matched comment into the master list
                                ListOfMatchedComments.append(individualMention.group())
                                print("Link: " + link)
                                TotalAFILinks += link + "\n\n"
                                TotalSearchLinks += searchLink + "\n\n"

**Comment by HadManySons** [comment]
Unfortunately, I don't know how to test it, since I can't duplicate the bug at will. I'll probably add a logging.error statement that I parse the log for.

**Comment by HadManySons** [comment]
Updated the code to try and catch and then discard a garbage return from ePubs. If this goes a week or so without vomiting on /r/airforce, I'll close this issue. Unless anyone else has a better solution?

**Comment by HadManySons** [comment]
So far, there have been no CDATA returns logged...

**Comment by HadManySons** [comment]
Hasn't happened since. Closing
