### ISSUE TITLE
Bot comments on court martial comments

### ISSUE THREAD

**Issue by HadManySons** [HadManySons/AFILinkerBot#4]
The bot thinks that references to court martial cases, "CAAF 2001" for example, are actually AF Forms.

https://www.reddit.com/r/AirForce/comments/6p4vqb/recoursed_if_directed_to_give_paperwork_you/dkmvsa3/

https://www.reddit.com/r/AirForce/comments/6p7el1/navy_e4_vs_air_force_e4/dko0gwm/

Need to add something to exclude things that start with "CAAF" as a possible catch.

**Comment by apex-omontgomery** [comment]
Looks like you fixed this with your regex change. https://regex101.com/r/LunhMp/1

**Comment by HadManySons** [comment]
No, the regex link you posted was in uppercase, where as the regex only looks for lowercase (which the bot converts everything to).  It has not been fixed yet.

**Comment by HadManySons** [comment]
This regex fixes it. Ignores an "af" if it preceeded by a "ca": https://regex101.com/r/LunhMp/2

((afi|afpd|afman|afva|afh|afji|afjman|afpam|afgm|afpci|aetci|usafai|afttp)[0-9]{1,2}-[0-9]{1,4}([0-9]{1})?([a-z]{1,2}-)?([0-9]{1,3})?(vol|v)?\d?)|(([^c][^a])(af|form|afform|sf|afto|afcomsec|afg|apda|aftd|imt|afimt|aetc)[0-9]{1,4}([a-z]{1,2})?)
