### ISSUE TITLE
Links are missing space between afi and the remaining text. 

### ISSUE THREAD

**Issue by apex-omontgomery** [HadManySons/AFILinkerBot#5]
AFI36-2606search link:
https://www.reddit.com/r/AirForce/comments/6vzap2/re_code_for_active_duty/dm5v26d/?context=3

line 180: add space to left side of ' search link....'

                        searchLink = '[' + str(
                            individualMention.group()).upper() + ' search link](http://www.e-publishing.af.mil/index' \
                                                                 '.asp?txtSearchWord=%s&btnG.x=28&btnG.y=4&client' \
                                                                 '=AFPW_EPubs&proxystylesheet=AFPW_EPubs&ie=UTF-8&oe=' \
                                                                 'UTF-8&output=xml_no_dtd&site=AFPW_EPubs)'\
                                                                 % individualMention.group()

**Comment by HadManySons** [comment]
So they, I never noticed that before. Will fix.

**Comment by HadManySons** [comment]
Fixed
